# Generated by Django 5.1.6 on 2025-02-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_profesion_alter_frasedb_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesion',
            new_name='ProfesionDb',
        ),
    ]
